# Use cargo make to run scripts in this file. Most scripts are used to provide safe defaults for
# standard operations (generate docs with mermaid and KaTeX support, run benchmarks with shilds_up
# disabled, ...)

# Enable docs with Mermaid, KaTeX and some small design tweaks.
[tasks.prepare-aeon-models]
command = "cargo"
args = ["run", "--release", "--bin", "prepare_aeon_models", "benchmarks_real_life"]

[tasks.prepare-bnet-models]
command = "cargo"
dependencies = ["prepare-aeon-models"]
args = ["run", "--release", "--bin", "aeon_to_bnet", "benchmarks_real_life", "benchmarks_real_life"]